AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Cost Watcher - Keeping tabs on your spend"

Parameters:
  AccountWarningLevel:
    Default: 300
    Description: 'Per account: Warning level for monthly cost ($).'
    Type: Number
  AccountDangerLevel:
    Default: 500
    Description: 'Per account: Danger level for monthly cost ($).'
    Type: Number
  DetailWarningLevel:
    Default: 100
    Description: 'Service detail queries: Warning level for monthly cost ($).'
    Type: Number
  DetailDangerLevel:
    Default: 200
    Description: 'Service detail queries: Danger level for monthly cost ($).'
    Type: Number
  NotificationTime:
    Default: '3'
    Description: 'Notification time in 24-hour notation (UTC). (0-23)'
    Type: Number
  SlackWebHookUrl:
    Default: https://hooks.slack.com/services/abcd/efgh/ijkl
    Description: 'Incoming webhook URL from Slack.'
    Type: String

Resources:
  ApiGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "CostWatcher"
      Description: "Cost Watcher API for incoming slack messages"

  ApiGatewayRootMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "POST"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArnDispatch}/invocations"
          - LambdaArnDispatch: !GetAtt "LambdaFunctionCWDispatch.Arn"
      ResourceId: !GetAtt "ApiGateway.RootResourceId"
      RestApiId: !Ref "ApiGateway"

  ApiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    Properties:
      RestApiId: !Ref "ApiGateway"
      StageName: "prod"
    DependsOn: "ApiGatewayRootMethod"

  LambdaFunctionCWDispatch:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: ./scripts/CostWatcherDispatch.py
      Description: "Cost Watcher - Dispatcher lambda to acknowledge a slash command and kick off the detail lookup"
      Environment:
        Variables:
          SNSTopicArn: !Join ["", ["arn:aws:sns:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId",":",!GetAtt "SNSTopic.TopicName"]]
      FunctionName: "CostWatcherDispatch"
      Handler: "CostWatcherDispatch.lambda_handler"
      MemorySize: 128
      Role: !GetAtt "LambdaExecutionRole.Arn"
      Runtime: "python3.7"
      Timeout: 90


  LambdaFunctionCWAccount:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: ./scripts/CostWatcherAccount.py
      Description: "Cost Watcher - Returns the account daily and monthly costs to slack"
      Environment:
        Variables:
          AccountDangerLevel: !Ref "AccountDangerLevel"
          AccountWarningLevel: !Ref "AccountWarningLevel"
          SlackWebHookUrl: !Ref "SlackWebHookUrl"
      FunctionName: "CostWatcherAccount"
      Handler: "CostWatcherAccount.lambda_handler"
      MemorySize: 128
      Role: !GetAtt "LambdaExecutionRole.Arn"
      Runtime: "python3.7"
      Timeout: 90


  LambdaFunctionCWDetail:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: ./scripts/CostWatcherDetail.py
      Description: "Cost Watcher - Returns the service breakdown for an account to slack"
      Environment:
        Variables:
          DetailDangerLevel: !Ref "DetailDangerLevel"
          DetailWarningLevel: !Ref "DetailWarningLevel"
      FunctionName: "CostWatcherDetail"
      Handler: "CostWatcherDetail.lambda_handler"
      MemorySize: 128
      Role: !GetAtt "LambdaExecutionRole.Arn"
      Runtime: "python3.7"
      Timeout: 90


  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "CostWatcherDispatch"
      Subscription:
        - Endpoint: !GetAtt "LambdaFunctionCWDetail.Arn"
          Protocol: lambda


  LambdaCronEvent:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 0 * * ? *)
      Targets:
        - Arn:
            !GetAtt "LambdaFunctionCWAccount.Arn"
          Id:
            !Ref "LambdaFunctionCWAccount"

  LambdaInvokePermissionCron:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt "LambdaFunctionCWAccount.Arn"
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt "LambdaCronEvent.Arn"

  LambdaInvokePermissionSNS:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt "LambdaFunctionCWDetail.Arn"
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref "SNSTopic"

  LambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt "LambdaFunctionCWDispatch.Arn"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/POST/"

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: 
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service: 
                - "lambda.amazonaws.com"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "organizations:DescribeAccount"
                  - "ce:GetCostAndUsage"
                Effect: Allow
                Resource: '*'
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/CostWatcherAccount:*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/CostWatcherDetail:*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/CostWatcherDispatch:*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Action:
                  - "sns:Publish"
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:CostWatcherDispatch"
          PolicyName: "CostWatcher"

  LambdaLogGroupDispatch:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaFunctionCWDispatch}"
      RetentionInDays: 90

  LambdaLogGroupAccount:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaFunctionCWAccount}"
      RetentionInDays: 90

  LambdaLogGroupDetail:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaFunctionCWDetail}"
      RetentionInDays: 90


Outputs:
  ApiGatewayInvokeURL:
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"

  LambdaArnDispatch:
    Value: !GetAtt "LambdaFunctionCWDispatch.Arn"

  LambdaArnAccount:
    Value: !GetAtt "LambdaFunctionCWAccount.Arn"

  LambdaArnDetail:
    Value: !GetAtt "LambdaFunctionCWDetail.Arn"